### ISSUE TITLE
Issue while running make command - executable files  ccov,bam2cov not generated

### ISSUE THREAD

**Issue by Vithyanatarajan** [SJTU-CGM/HUPAN#1]
make[1]: Entering directory '/home/vithya/HUPAN-v1.02/src/bam2cov'make[1]: Entering directory '/home/vithya/HUPAN-v1.02/src/bam2cov'
g++ -O2 -o ../../bin/bam2cov bam2cov.cpp -lbamtools -L ../../lib/ -I ../../lib/include/
/tmp/ccXIj7M8.o: In function `main':
bam2cov.cpp:(.text.startup+0xbf): undefined reference to `BamTools::BamReader::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target '../../bin/bam2cov' failed
make[1]: *** [../../bin/bam2cov] Error 1
make[1]: Leaving directory '/home/vithya/HUPAN-v1.02/src/bam2cov'
make[1]: Entering directory '/home/vithya/HUPAN-v1.02/src/ccov'
g++ -O2 -o ../../bin/ccov CCOV.cpp GTF.cpp -lz -lbamtools -L ../../lib/ -I ../../lib/include/
/tmp/ccrbuPx3.o: In function `main':
CCOV.cpp:(.text.startup+0x1ed): undefined reference to `BamTools::BamReader::Open(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target '../../bin/ccov' failed
make[1]: *** [../../bin/ccov] Error 1
make[1]: Leaving directory '/home/vithya/HUPAN-v1.02/src/ccov'
make[1]: Entering directory '/home/vithya/HUPAN-v1.02/src/perl'
make[1]: Leaving directory '/home/vithya/HUPAN-v1.02/src/perl'
make[1]: Entering directory '/home/vithya/HUPAN-v1.02/src/R'
make[1]: Leaving directory '/home/vithya/HUPAN-v1.02/src/R'

**Comment by zhqduan** [comment]
This bug is caused by the higher version of gcc (gcc version 8.3.1).
We have fixed this bug.
