### ISSUE TITLE
In "hupan assemble sga", the "-m" option is not work !!!

### ISSUE THREAD

**Issue by Bobo22331** [SJTU-CGM/HUPAN#2]
When I use the command 
`$ hupan assemble sga -t 18 -d 60 -m 1 fastq_data output_directory sga_directory` ,
it only output the hupan usage, but not work.
When I remove the `-m` option, it will work. So, what's the problem with the HUPAN ? Thank you!

**Comment by zhqduan** [comment]
Thanks for pointing out this issue. I have corrected this bug and it works now. Please re-download HUPAN.

**Comment by Bobo22331** [comment]
Thank you!
