### ISSUE TITLE
“Extract non-reference sequences from assembled contigs” couldn't find assembly file

### ISSUE THREAD

**Issue by chenshixuan** [SJTU-CGM/HUPAN#4]
My software was  donwnloaded 4 days ago.
Using command "hupanSLURM alignContig"  cannot find assembly file with the assembly result;
My conmmand are  "HUPAN/bin/hupanSLURM alignContig   -t 20 Hupan/01data/ExampleData/asemble/     aligned_result         /bin/mummer-4.0.0beta2/   Hupan/01data/ExampleData/ref/chr22.fa"
my assembly files are "/Hupan/01data/ExampleData/asemble/soapdenovo1/" ,"/Hupan/01data/ExampleData/asemble/soapdenovo2/" “/Hupan/01data/ExampleData/asemble/soapdenovo3/”，aseebly  files *.scafSeq and *.contig 
 exist.
  Thank you for your helping to solve the  problem.

**Comment by zhqduan** [comment]
Thank you very much for testing HUPAN!
As you described, the suffix of assembled files were not match to the default (contig.fa). 
Therefore you should specify the options "-s" in your command as follow:
 HUPAN/bin/hupanSLURM alignContig -t 20 -s contig Hupan/01data/ExampleData/asemble/ aligned_result /bin/mummer-4.0.0beta2/ Hupan/01data/ExampleData/ref/chr22.fa
Alternatively, you can also rename the assembly files by the suffix "contig.fa", and conduct the command as you mentioned earlier.

**Comment by chenshixuan** [comment]
Thank you for your help.
when I changed as your suggestion,another error log is "Can't exec "sbatch": No such file or directory at  HUPAN/HUPAN/lib/HUPANrmHighSLURM.pm ‘’。The software is used by  the SLURM system，not suit for my SGE system。Could you have some suggestions  to suit for SGE system？
Another question， dose the software  suit for plant genomes？
Thank you ！

**Comment by zhqduan** [comment]
The HUPAN is designed for LSF system and SLURM system. If you are skilled in perl program, you could modify the scripts in HUPAN/lib. All the files of *SLURM.pm or *LSF.pm contain the note "##Might be modified for different task submission system##". You only have to change the related codes to match for SGE system. I am very sorry that I am unfamiliar with the SGE system.
HUPAN is designed to conduct pan-genome analysis of eukaryote, like human with large genome size, and it is suit for plant genomes.

**Comment by chenshixuan** [comment]
I have found  HUPAN/bin/hupan can  skip using the SLURM syetem，now it is running .
Thanyou ！
