### ISSUE TITLE
‘getUnalnCtg’ function has some new  problem

### ISSUE THREAD

**Issue by chenshixuan** [SJTU-CGM/HUPAN#5]
When Use  HUPAN with the  command "/HUPAN/bin/hupan  getUnalnCtg -p  contig  /Hupan/02test/02step2_extracseq/candidate/data/   Hupan/02test/03step3/quast_result/data/  Unalign_result" ,the error messge is "Error04: cannot open data directory: /Hupan/02test/03step3/quast_result/data/sample1/contigs_reports/nucmer_output/" .Actually,the output directory's name is "minimap_output" ,not the "nucmer_output".
However, the program is still runnin with the command "hupan  getUnalnCtg",the two  output result directories are "quast_result  ,    Unalign_result".The "quast_result" is same to the commmad  "hupan assemSta" output result,So why this step is same to the last step ?Compute twice! Now the  Unalign_result still empty. 
Thank you very much!

**Comment by zhqduan** [comment]
As you described, this error is caused by the higher version of QUAST you used. In QUAST 5.0 or higher, the new fast aligner software 'minimap2' is used (http://quast.sourceforge.net/quast-lg.html). However, HUPAN is designed for results from nucmer. Please use QUAST 4.5

**Comment by chenshixuan** [comment]
OK，thank you very much
